services:
  first:
    cap_add:
    - SYS_PTRACE
    command:
    - ./kaspad
    - --devnet
    - --acceptanceindex
    - --nodnsseed
    - --miningaddr=kaspadev:qpzugm9c0r0nrtrha3jhqqty0aj976xa8qxr3t8zte
    - --rpcuser=user
    - --rpcpass=pass
    - --rpclisten=127.0.0.1:16615
    - --rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert
    - --rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key
    - --notls
    image: kaspad:latest
    network_mode: host
    ports:
    - 16615:16615
    - 16611:16611
    security_opt:
    - apparmor=unconfined
    volumes:
    - ~/volumes/kaspad/:/root/.kaspad
  second:
    cap_add:
    - SYS_PTRACE
    command:
    - ./kaspad
    - --devnet
    - --acceptanceindex
    - --connect=127.0.0.1:16611
    - --rpcuser=user
    - --rpcpass=pass
    - --miningaddr=kaspadev:qqfrfccgpw75zdw28veslhzzdx0jn97dcqrat4tmuh
    - --rpclisten=127.0.0.1:16616
    - --rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert
    - --rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key
    - --notls
    image: kaspad:latest
    network_mode: host
    ports:
    - 16616:16616
    security_opt:
    - apparmor=unconfined
  second-debug:
    cap_add:
    - SYS_PTRACE
    command:
    - dlv
    - --listen=:40000
    - --api-version=2
    - --headless=true
    - exec
    - ./kaspad
    - --
    - --devnet
    - --addrindex
    - --acceptanceindex
    - --connect=127.0.0.1:16611
    - --rpcuser=user
    - --rpcpass=pass
    - --miningaddr=kaspadev:qqfrfccgpw75zdw28veslhzzdx0jn97dcqrat4tmuh
    - --rpclisten=127.0.0.1:16616
    - --rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert
    - --rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key
    - --notls
    image: kaspad:latest
    network_mode: host
    ports:
    - 16615:16615
    - 40000:40000
    security_opt:
    - apparmor=unconfined
version: '3'
