version: '3'
services:
  kaspad-first:
    cap_add:
      - SYS_PTRACE
    image: kaspad:latest
    volumes:
    - ~/volumes/kaspad/:/.kaspad
    - /home/yuval/keys:/go/src/github.com/kaspanet/devops/devnet/common
    command:
      - "./kaspad"
      - "--devnet"
      - "--acceptanceindex"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpclisten=0.0.0.0:16615"
      - "--rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert"
      - "--rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key"
      - "--debuglevel=debug"
      - "--profile=6061"
    ports:
      - "16615:16615"
      - "16611:16611"
      - "6061:6061"
    user: 1000:1000
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_first
  kaspad-second:
    cap_add:
      - SYS_PTRACE
    image: kaspad:latest
    volumes:
    - ~/keys:/go/src/github.com/kaspanet/devops/devnet/common
    command:
      - ./kaspad
      - "--devnet"
      - "--acceptanceindex"
      - "--connect=127.0.0.1:16611"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpclisten=0.0.0.0:16616"
      - "--rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert"
      - "--rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key"
      - "--debuglevel=debug"
      - "--profile=6062"
    ports:
      - "16616:16616"
      - "6062:6062"
    user: root
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_second
  kaspad-builder-1:
    cap_add:
      - SYS_PTRACE
    image: kaspad:latest
    volumes:
      - ~/volumes/build/:/.kaspad
      - /home/yuval/keys:/go/src/github.com/kaspanet/devops/devnet/common
    command:
      - "./kaspad"
      - "--devnet"
      - "--acceptanceindex"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpclisten=0.0.0.0:16650"
      - "--rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert"
      - "--rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key"
      - "--debuglevel=debug"
      - "--profile=6061"
    ports:
      - "16650:16650"
      - "16611:16661"
      - "6061:6061"
    user: 1000:1000
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_builder-1
  kaspad-builder-2:
    cap_add:
      - SYS_PTRACE
    image: kaspad:latest
    volumes:
      - /home/yuval/keys:/go/src/github.com/kaspanet/devops/devnet/common
    command:
      - "./kaspad"
      - "--devnet"
      - "--connect=127.0.0.1:16661"
      - "--acceptanceindex"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpclisten=0.0.0.0:16650"
      - "--rpccert=/go/src/github.com/kaspanet/devops/devnet/common/rpc.cert"
      - "--rpckey=/go/src/github.com/kaspanet/devops/devnet/common/rpc.key"
      - "--debuglevel=debug"
      - "--profile=6061"
    ports:
      - "16650:16650"
      - "6061:6061"
    user: 1000:1000
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_builder-2
  kasparov_migrate:
    image: "kasparov-sync:latest"
    command:
      - "/app/kasparov-syncd"
      - "--rpcserver=127.0.0.1:16616"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--migrate"
      - "--notls"
      - "--dbaddress=172.17.0.1:5432"
      - "--dbname=kasparov"
      - "--dbuser=dbuser"
      - "--dbpass=password"
      - "--devnet"
    user: root
    network_mode: host
    container_name: localrun_kasparov_migrate

  kasparovd:
    image: "kasparovd:latest"
    command:
      - "/app/kasparovd"
      - "--rpcserver=127.0.0.1:16616"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpccert=/root/.kasparov/rpc.cert"
      - "--dbaddress=127.0.0.1:5432"
      - "--dbname=kasparov"
      - "--dbuser=dbuser"
      - "--dbpass=password"
      - "--devnet"
      - "-d=debug"
    ports:
      - "8080:8080"
    user: root
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_kasparovd

  kasparovsyncd:
    image: "kasparov-sync:latest"
    command:
      - "/app/kasparov-syncd"
      - "--rpcserver=127.0.0.1:16616"
      - "--rpcuser=user"
      - "--rpcpass=pass"
      - "--rpccert=/root/.kasparov/rpc.cert"
      - "--dbaddress=127.0.0.1:5432"
      - "--dbname=kasparov"
      - "--dbuser=dbuser"
      - "--dbpass=password"
      - "--devnet"
      - "-d=debug"
    user: root
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    container_name: localrun_kasparov_syncd

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: kasparov
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    container_name: localrun_postgres
